apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-service
  namespace: default
  labels:
    app: ping-pong
    service: pong
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ping-pong
      service: pong
  template:
    metadata:
      labels:
        app: ping-pong
        service: pong
    spec:
      containers:
        - name: pong-service
          image: "lreimer/spring-boot-app:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-management
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 5
            failureThreshold: 30
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: MANAGEMENT_SERVER_PORT
              value: '8081'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.tempo:4317
            - name: OTEL_SERVICE_NAME
              value: ping-service
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: pod=$(KUBE_POD_NAME),namespace=default
            - name: OTEL_METRICS_EXPORTER
              value: none